<a href="https://colab.research.google.com/github/LeeKeYin/data_science_w1/blob/main/Copy_of_wia1007TW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

In [ ]:
print("=== Part 1: NumPy Array Operations ===\n")

=== Part 1: NumPy Array Operations ===



In [ ]:
#1.Create a numpy array of size 2 x 2
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
#2.Create a random numpy array of size 3 x 4
b=np.random.random((3,4))
print(b)
print(f"Shape: {b.shape}\n")

[[0.12906903 0.97604122 0.3997539  0.10039574]
 [0.96866734 0.72013008 0.56431631 0.64699011]
 [0.21505257 0.17303918 0.36212368 0.02006949]]
Shape: (3, 4)



In [ ]:
#3.Create a numpy array of ones and a numpy array of zeroes
c=np.zeros((2,2))
d=np.ones((4,3))
print(c)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#4.Create a random numpy array of size 6x3 and transpose it
e=np.random.random((6,3))
print(e)
print(np.transpose(e))

[[0.0273134  0.22849039 0.64901154]
 [0.05452209 0.00619418 0.69708644]
 [0.87698838 0.17387362 0.54137258]
 [0.58354357 0.49381003 0.95971315]
 [0.69554168 0.64736833 0.80448446]
 [0.81212599 0.47486107 0.57970051]]
[[0.0273134  0.05452209 0.87698838 0.58354357 0.69554168 0.81212599]
 [0.22849039 0.00619418 0.17387362 0.49381003 0.64736833 0.47486107]
 [0.64901154 0.69708644 0.54137258 0.95971315 0.80448446 0.57970051]]


In [ ]:
#5.Create two random numpy array of size n x p and p x m and then compute the dot product
n,p,m=2,3,4
f=np.random.random((n,p))
g=np.random.random((p,m))
print(f"f ({n}x{p}): ")
print(f)
print(f"\ng ({p}x{m}): ")
print(g)
result=np.dot(f,g)
print(f"\nDot Product Result ({n}x{m}): ")
print(result)
print(f"Dot product shape: {result.shape}")

f (2x3): 
[[0.61098441 0.26285479 0.31934037]
 [0.82627064 0.17766094 0.25772758]]

g (3x4): 
[[0.48375561 0.05911763 0.6576074  0.18053677]
 [0.51832201 0.96688951 0.3292612  0.5435564 ]
 [0.15532115 0.03037369 0.78387748 0.08330567]]

Dot Product Result (2x4): 
[[0.48141087 0.29997103 0.73865947 0.27978441]
 [0.53182918 0.2284538  0.80388539 0.26721114]]
Dot product shape: (2, 4)
